### ISSUE TITLE
Filter by tags

### ISSUE THREAD

**Issue by Mosslar** [nixys/nxs-go-zabbix#1]
Hi,
Is posible to filter by tags?

I'll try:

`
	hObjects, _, err := z.HostGet(zabbix.HostGetParams{
		SelectTags: zabbix.SelectExtendedOutput,
		GetParameters: zabbix.GetParameters{
			Limit: 3,
			Filter: map[string]interface{}{
				"tags": zabbix.HostTagObject{Tag: "Backup", Value: "1", Operator: 0},
			},
			Output: zabbix.SelectExtendedOutput,
		},
	})
	for _, h := range hObjects {
		fmt.Println(h.HostID, ";", h.Host, ";", h.Tags, ";")
	}

`
but it's not working, show all hosts.

And how filter multiple tags?

**Comment by borisershov** [comment]
Hi!

In accordance with [official Zabbix API documentation for v5.0](https://www.zabbix.com/documentation/5.0/manual/api/reference/host/get) you may use `tags` parameter to filter hosts by tags. So your code can be changed as follows:

```
hObjects, _, err := z.HostGet(zabbix.HostGetParams{
	SelectTags: zabbix.SelectExtendedOutput,
	GetParameters: zabbix.GetParameters{
		Limit:  3,
		Output: zabbix.SelectExtendedOutput,
	},
	Tags: []zabbix.HostTagObject{
		{
			Tag:      "Backup",
			Value:    "1",
			Operator: 0,
		},
	},
})
for _, h := range hObjects {
	fmt.Println(h.HostID, ";", h.Host, ";", h.Tags, ";")
}
```

**Comment by AndreiMuvila** [comment]
@Mosslar Good afternoon. Is this issue still active?

**Comment by Mosslar** [comment]
Oh no, i forget close this issue :)
Sorry.
